### ISSUE TITLE
[Bug] Crash On Startup After Updating To 0.10.0

### ISSUE THREAD

**Issue by sonickai46** [Monika-After-Story/MonikaModDev#4685]
I updated to 0.10.0 through the game, then once I start the game, it crashes immediately. When it crashes it leaves the same traceback.txt each time. This is the .txt:

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-holidays.rpy", line 111, in <module>
TypeError: __init__() got an unexpected keyword argument 'start_dt'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Games 2\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "D:\Games 2\Doki Doki Literature Club\renpy\main.py", line 419, in main
    game.context().run(node)
  File "lib/windows-i686/script-holidays.rpyc", line 76, in script
  File "D:\Games 2\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Games 2\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script-holidays.rpy", line 111, in <module>
TypeError: __init__() got an unexpected keyword argument 'start_dt'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by multimokia** [comment]
Screenshot of your `game/` folder, please?

**Comment by sonickai46** [comment]
![capture4](https://user-images.githubusercontent.com/53128705/64916061-460fe580-d73b-11e9-9e93-70bc379838f7.PNG)
![Capture](https://user-images.githubusercontent.com/53128705/64916062-460fe580-d73b-11e9-8c6e-f34f0fbbc5a9.PNG)
![capture2](https://user-images.githubusercontent.com/53128705/64916063-46a87c00-d73b-11e9-85a2-415946b1ae04.PNG)
![capture3](https://user-images.githubusercontent.com/53128705/64916064-46a87c00-d73b-11e9-96ee-a1f90d43b2b5.PNG)

**Comment by multimokia** [comment]
you installed the source code version at some point. Delete all `.rpy` (not `.rpyc`) files and re-install version 0.10.0 manually.

**Comment by ThePotatoGuy** [comment]
[closing as resolved]
