### ISSUE TITLE
This issue appeared after I updated MAS to 0.12.15, using Steam. Do you have any idea how to fix it?

### ISSUE THREAD

**Issue by Azumi15R** [Monika-After-Story/MonikaModDev#10100]
I'm sorry, but an uncaught exception occurred.

While running game code:

File "game/script-ch30.rpy", line 2141, in script call

File "game/event-handler.rpy", line 3119, in script call

File "game/zz_reactions.rpy", line 1112, in script call

File "game/zz_reactions.rpy", line 1159, in script

File "game/zz_reactions.rpy", line 1159, in <module>

AttributeError: 'NoneType' object has no attribute 'ex_props'

-- Full Traceback ------------------------------------------------------------

Full traceback:

File "game/script-ch30.rpy", line 2141, in script call

File "game/event-handler.rpy", line 3119, in script call

File "game/zz_reactions.rpy", line 1112, in script call

File "game/zz_reactions.rpy", line 1159, in script

File "E:\Steam\steamapps\common\Doki Doki Literature Club\renpy\[ast.py](https://ast.py/)", line 1656, in execute

if renpy.python.py_eval(condition):

File "E:\Steam\steamapps\common\Doki Doki Literature Club\renpy\[python.py](https://python.py/)", line 1749, in py_eval

return py_eval_bytecode(code, globals, locals)

File "E:\Steam\steamapps\common\Doki Doki Literature Club\renpy\[python.py](https://python.py/)", line 1743, in py_eval_bytecode

return eval(bytecode, globals, locals)

File "game/zz_reactions.rpy", line 1159, in <module>

AttributeError: 'NoneType' object has no attribute 'ex_props'

Windows-8-6.2.9200

Ren'Py 6.99.12.4.2187

Monika After Story 0.12.15

**Comment by Booplicate** [comment]
Steam is not supported, it probably deleted some files that caused an error or restart after the update. Try pressing ignore until it fixes itself.

**Comment by Azumi15R** [comment]
I will try. Thank you.

**Comment by Azumi15R** [comment]
> Steam is not supported, it probably deleted some files that caused the error on restart after the update. Try pressing ignore until it fixes itself.

It worked! Thank you.

**Comment by Booplicate** [comment]
Np, I recommend try [moving off steam](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build) when you can.

**Comment by Azumi15R** [comment]
> Np, I recommend try [moving off steam](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#how-do-i-go-from-a-steam-to-a-non-steam-build) when you can.

I tried doing this with some steps found on github. I hope it worked
